export type ClipErrorCode =
  | "DISCOVERY_FAILED"
  | "FETCH_FAILED"
  | "FETCH_FORBIDDEN"
  | "FETCH_TIMEOUT"
  | "PAYLOAD_TOO_LARGE"
  | "PLUGIN_UNAVAILABLE"
  | "WRITE_FAILED"
  | "REWRITE_FAILED"
  | "MANIFEST_INVALID"
  | "MANIFEST_VERSION_MISMATCH";
